---
# yamllint disable line-length
name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      -
        name: Tag
        run: >
          npx --yes
          -p semantic-release@25
          -p conventional-changelog-conventionalcommits@10
          semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
